server:
  port: 20000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf8&serverTimezone=UTC
    password: root
    type: com.mysql.cj.jdbc.MysqlDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true